/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 8ae047cbe12075a658f94feab4d397ff)
interface __BaseEnv_Env {
	RELAY_ROOM: DurableObjectNamespace<import("./src/index").RelayRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "RelayRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
