/**
 * Closed allowlist of renderer operations that target one explicit TermLoop
 * connection source. The preload builds one named function per entry; this is
 * not a generic control-method bridge.
 */
export const PROFILED_DESKTOP_OPERATIONS = {
  systemInfo: "termloop:system-info",
  keepAwakeGet: "termloop:keep-awake-get",
  keepAwakeSet: "termloop:keep-awake-set",
  voiceSettingsGet: "termloop:voice-settings-get",
  voiceCredentialsSet: "termloop:voice-credentials-set",
  mcpToolSettingsGet: "termloop:mcp-tool-settings-get",
  mcpToolDescriptionUpdate: "termloop:mcp-tool-description-update",
  mcpToolDescriptionReset: "termloop:mcp-tool-description-reset",
  skillCatalogGet: "termloop:skill-catalog-get",
  skillDeploymentSet: "termloop:skill-deployment-set",
  skillDefinitionGet: "termloop:skill-definition-get",
  skillDefinitionSave: "termloop:skill-definition-save",
  skillDefinitionCreate: "termloop:skill-definition-create",
  contextBankCatalogGet: "termloop:context-bank-catalog-get",
  contextBankFileGet: "termloop:context-bank-file-get",
  contextBankFileSave: "termloop:context-bank-file-save",
  contextBankSiblingConflictResolve: "termloop:context-bank-sibling-conflict-resolve",
  projectList: "termloop:project-list",
  projectTaskAutomationGet: "termloop:project-task-automation-get",
  projectTaskAutomationSet: "termloop:project-task-automation-set",
  projectWorktreeSummary: "termloop:project-worktree-summary",
  projectWorktreeChangeList: "termloop:project-worktree-change-list",
  projectWorktreeDiff: "termloop:project-worktree-diff",
  projectWorktreePreImage: "termloop:project-worktree-pre-image",
  projectCreate: "termloop:project-create",
  projectUpdate: "termloop:project-update",
  projectDelete: "termloop:project-delete",
  projectListLocalBranches: "termloop:project-list-local-branches",
  taskList: "termloop:task-list",
  taskWorktreeChangeList: "termloop:task-worktree-change-list",
  taskWorktreeDiff: "termloop:task-worktree-diff",
  taskWorktreePreImage: "termloop:task-worktree-pre-image",
  taskBranchCommitSummaryList: "termloop:task-branch-commit-summary-list",
  taskBranchCommitList: "termloop:task-branch-commit-list",
  taskBranchCommitChangeList: "termloop:task-branch-commit-change-list",
  taskBranchCommitDiff: "termloop:task-branch-commit-diff",
  gitHostPullRequestList: "termloop:git-host-pull-request-list",
  gitHostPullRequestChangeList: "termloop:git-host-pull-request-change-list",
  gitHostPullRequestDiff: "termloop:git-host-pull-request-diff",
  openExternal: "termloop:open-external",
  copySessionId: "termloop:copy-session-id",
  taskInspectWorktreeCleanup: "termloop:task-inspect-worktree-cleanup",
  taskCleanupWorktree: "termloop:task-cleanup-worktree",
  taskForgetStaleWorktree: "termloop:task-forget-stale-worktree",
  taskDiscardStaleWorktree: "termloop:task-discard-stale-worktree",
  taskInspectWorktreeRepair: "termloop:task-inspect-worktree-repair",
  taskRepairWorktree: "termloop:task-repair-worktree",
  taskDismissWorktreeRepair: "termloop:task-dismiss-worktree-repair",
  taskBindBranch: "termloop:task-bind-branch",
  taskProvisionWorktree: "termloop:task-provision-worktree",
  taskDismissWorktreeProvisioning: "termloop:task-dismiss-worktree-provisioning",
  taskTerminalLaunch: "termloop:task-launch-terminal",
  taskStartRun: "termloop:task-start-run",
  taskRestartRun: "termloop:task-restart-run",
  projectStartRun: "termloop:project-start-run",
  projectRestartRun: "termloop:project-restart-run",
  taskAgentPreview: "termloop:task-preview-agent",
  taskAgentLaunch: "termloop:task-launch-agent",
  taskCreate: "termloop:task-create",
  taskRename: "termloop:task-rename",
  taskUpdateBrief: "termloop:task-update-brief",
  taskClose: "termloop:task-close",
  taskFinalizeClosedWorktreeRemoval: "termloop:task-finalize-closed-worktree-removal",
  taskInspectArchive: "termloop:task-inspect-archive",
  taskArchive: "termloop:task-archive",
  taskAbandonArchive: "termloop:task-abandon-archive",
  taskRestore: "termloop:task-restore",
  taskArchivedContext: "termloop:task-archived-context",
  taskReopen: "termloop:task-reopen",
  taskDelete: "termloop:task-delete",
  taskDeleteArchived: "termloop:task-delete-archived",
  defaultProjectsRoot: "termloop:default-projects-root",
  browseDirectory: "termloop:browse-directory",
  sessionList: "termloop:session-list",
  sessionListArchived: "termloop:session-list-archived",
  sessionListDeleted: "termloop:session-list-deleted",
  sessionInspectArchive: "termloop:session-inspect-archive",
  sessionArchive: "termloop:session-archive",
  sessionRestoreArchived: "termloop:session-restore-archived",
  sessionDeleteArchived: "termloop:session-delete-archived",
  sessionRestoreDeleted: "termloop:session-restore-deleted",
  agentStatusList: "termloop:agent-status-list",
  agentCapabilityList: "termloop:agent-capability-list",
  stewardConfigurationGet: "termloop:steward-configuration-get",
  stewardConfigurationSet: "termloop:steward-configuration-set",
  stewardConfigurationDelete: "termloop:steward-configuration-delete",
  workerConfigurationList: "termloop:worker-configuration-list",
  workerConfigurationCreate: "termloop:worker-configuration-create",
  workerConfigurationUpdate: "termloop:worker-configuration-update",
  workerConfigurationDelete: "termloop:worker-configuration-delete",
  runConfigurationList: "termloop:run-configuration-list",
  runConfigurationCreate: "termloop:run-configuration-create",
  runConfigurationUpdate: "termloop:run-configuration-update",
  runConfigurationDelete: "termloop:run-configuration-delete",
  runConfigurationImprovePreview: "termloop:run-configuration-improve-preview",
  runConfigurationImproveLaunch: "termloop:run-configuration-improve-launch",
  settingsImprovePreview: "termloop:settings-improve-preview",
  settingsImproveLaunch: "termloop:settings-improve-launch",
  assistantPromptImprovePreview: "termloop:assistant-prompt-improve-preview",
  assistantPromptImproveLaunch: "termloop:assistant-prompt-improve-launch",
  configurationVersionList: "termloop:configuration-version-list",
  configurationVersionRestore: "termloop:configuration-version-restore",
  runRuntimeList: "termloop:run-runtime-list",
  routineConfigurationList: "termloop:routine-configuration-list",
  routineConfigurationCreate: "termloop:routine-configuration-create",
  routineConfigurationUpdate: "termloop:routine-configuration-update",
  routineContextUpdate: "termloop:routine-context-update",
  routineConfigurationDelete: "termloop:routine-configuration-delete",
  routineRuntimeList: "termloop:routine-runtime-list",
  routineRunNow: "termloop:routine-run-now",
  taskSourceList: "termloop:task-source-list",
  taskSourceBoardList: "termloop:task-source-board-list",
  taskSourceBoardListStored: "termloop:task-source-board-list-stored",
  taskSourceStatusList: "termloop:task-source-status-list",
  taskSourceStatusListStored: "termloop:task-source-status-list-stored",
  taskSourceCreate: "termloop:task-source-create",
  taskSourceUpdate: "termloop:task-source-update",
  taskSourceConnect: "termloop:task-source-credentials-set",
  taskSourceDelete: "termloop:task-source-delete",
  taskSourceRefresh: "termloop:task-source-refresh",
  taskSourceCandidateList: "termloop:task-source-candidate-list",
  taskSourceCandidateImport: "termloop:task-source-candidate-import",
  taskSourceCandidateIgnore: "termloop:task-source-candidate-ignore",
  taskSourceCandidateUnignore: "termloop:task-source-candidate-unignore",
  playbookGet: "termloop:playbook-get",
  playbookRuntime: "termloop:playbook-runtime",
  playbookTaskPositionSet: "termloop:playbook-task-position-set",
  playbookUpdate: "termloop:playbook-update",
  companionTranscriptList: "termloop:companion-transcript-list",
  companionTranscriptAppend: "termloop:companion-transcript-append",
  companionProposalRespond: "termloop:companion-proposal-respond",
  companionSuggestionAccept: "termloop:companion-suggestion-accept",
  companionTranscriptClear: "termloop:companion-transcript-clear",
  notifyAgentAttention: "termloop:agent-attention-notify",
  sessionRename: "termloop:session-rename",
  terminalLaunch: "termloop:terminal-launch",
  agentPreview: "termloop:agent-preview",
  agentLaunch: "termloop:agent-launch",
  quickActionPasteImage: "termloop:quick-action-paste-image",
  quickActionRestoreImage: "termloop:quick-action-restore-image",
  quickActionDiscardImage: "termloop:quick-action-discard-image",
  quickActionPreview: "termloop:quick-action-preview",
  quickActionLaunch: "termloop:quick-action-launch",
  sessionTerminate: "termloop:session-terminate",
  sessionPreviewResumeAgent: "termloop:session-preview-resume-agent",
  sessionResumeAgent: "termloop:session-resume-agent",
  sessionRestartAgent: "termloop:session-restart-agent",
  sessionPreviewRelocateAgent: "termloop:session-preview-relocate-agent",
  sessionRelocateAgent: "termloop:session-relocate-agent",
  sessionPreviewRelocateAgentToProject: "termloop:session-preview-relocate-agent-to-project",
  sessionRelocateAgentToProject: "termloop:session-relocate-agent-to-project",
  sessionForkAgent: "termloop:session-fork-agent",
  sessionRepairProviderHistory: "termloop:session-repair-provider-history",
  sessionHistoryList: "termloop:session-history-list",
  sessionHistoryPreview: "termloop:session-history-preview",
  sessionHistoryPreviewResumeAgent: "termloop:session-history-preview-resume-agent",
  sessionHistoryResumeAgent: "termloop:session-history-resume-agent",
  sessionRequestAskTo: "termloop:session-request-ask-to",
  sessionRequestHandoverTo: "termloop:session-request-handover-to",
  sessionPasteImage: "termloop:session-paste-image",
  sessionClose: "termloop:session-close",
  terminalAttach: "termloop:terminal-attach",
} as const;

export type ProfiledDesktopOperationName = keyof typeof PROFILED_DESKTOP_OPERATIONS;
export type ProfiledIpcChannel = typeof PROFILED_DESKTOP_OPERATIONS[ProfiledDesktopOperationName];

const PROFILE_ID = /^(?:local|[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})$/u;

export type ConnectionProfileEnvelope = {
  readonly __termloopConnectionProfileId: string;
};

const PROFILED_IPC_CHANNELS = new Set<string>(Object.values(PROFILED_DESKTOP_OPERATIONS));

export function connectionProfileEnvelope(profileId: string): ConnectionProfileEnvelope {
  if (!PROFILE_ID.test(profileId)) throw new Error("invalidConnectionProfileId");
  return { __termloopConnectionProfileId: profileId };
}

export function parseConnectionProfileEnvelope(value: unknown): string | undefined {
  if (!value || typeof value !== "object") return undefined;
  const profileId = (value as Partial<ConnectionProfileEnvelope>).__termloopConnectionProfileId;
  return typeof profileId === "string" && PROFILE_ID.test(profileId) ? profileId : undefined;
}

export function isProfiledIpcChannel(channel: string): channel is ProfiledIpcChannel {
  return PROFILED_IPC_CHANNELS.has(channel);
}
